ci: update actions/checkout to v2
typicalbot/typicalbot pull request #223
Opened 2020-05-08 15:59 UTC by Skillz4Killz

## Pull Request

### Items Changed

- [ ] Commands
- [x] Events
- [ ] Handlers
- [ ] Structures
- [ ] Tasks
- [ ] Documentation
- [ ] Other: ______

### Description

This PR should fix an error that happens when the guild does not give the bot BAN_MEMBERS permission. 
![image](https://user-images.githubusercontent.com/23035000/81424095-64d84780-9123-11ea-9aad-d67fd2fca311.png)

### Issues

### Have You...?

- [ ] I have read the [Contributing Guidelines](https://github.com/typicalbot/typicalbot/blob/master/.github/CONTRIBUTING.md).
- [ ] I have completed the [pull request template](https://github.com/typicalbot/typicalbot/blob/master/.github/PULL_REQUEST_TEMPLATE.md).
- [ ] I have checked open [pull requests](https://github.com/typicalbot/typicalbot/pulls) for upcoming features and fixes.

2020-05-08 16:18 UTC, nsylke submitted a review, later dismissed

2020-05-08 21:08 UTC, tjrgg requested changes
This change would prevent logs from running. This check should wrap around functionality that checks to see if the user was banned instead of returning.

2020-05-08 22:23 UTC, Skillz4Killz commented
Good catch. Ill fix it next time im on VSC

2020-05-09 13:41 UTC, nsylke approved these changes

2020-05-09 17:26 UTC, tjrgg approved these changes

2020-05-09 18:08 UTC, merged