fix help mention bug
typicalbot/typicalbot pull request #289
Opened 2020-07-15 01:17 UTC by Skillz4Killz

## Pull Request

### Items Changed

- [x] Commands
- [ ] Events
- [ ] Handlers
- [ ] Structures
- [ ] Tasks
- [ ] Documentation
- [ ] Other: ______

### Description

This PR fixes the bug where you can @ users with the help command.

### Issues

### Have You...?

- [ ] I have read the [Contributing Guidelines](https://github.com/typicalbot/typicalbot/blob/master/.github/CONTRIBUTING.md).
- [ ] I have completed the [pull request template](https://github.com/typicalbot/typicalbot/blob/master/.github/PULL_REQUEST_TEMPLATE.md).
- [ ] I have checked open [pull requests](https://github.com/typicalbot/typicalbot/pulls) for upcoming features and fixes.

2020-07-15 01:17 UTC, Skillz4Killz commented
This remains to be testedas I was not able to disable the embed option to test it without the embed.

2020-07-15 02:07 UTC, tjrgg commented on src/commands/core/help.ts
> +            if (!message.embeddable) return message.error(response, undefined, { allowedMentions: { users: [message.author.id]}});
I'm not seeing how `TypicalMessage#error` currently takes in options? Only parameters it seems to take is `content` and `embed`.

2020-07-16 17:27 UTC, tjrgg approved these changes

2020-07-16 18:08 UTC, tjrgg requested changes
Unfortunately, these changes do not fix the problem.
![image](https://user-images.githubusercontent.com/11968358/87706614-6ba7ba00-c765-11ea-9b08-b7c67af6c235.png)

2020-07-16 18:57 UTC, tjrgg approved these changes

2020-07-16 18:59 UTC, merged