randuser multi option
typicalbot/typicalbot pull request #292
Opened 2020-07-24 15:55 UTC by Skillz4Killz

## Pull Request

### Items Changed

- [x] Commands
- [ ] Events
- [ ] Handlers
- [ ] Structures
- [ ] Tasks
- [ ] Documentation
- [ ] Other: ______

### Description

Allow multiple users to be selected.

### Issues

### Have You...?

- [ ] I have read the [Contributing Guidelines](https://github.com/typicalbot/typicalbot/blob/master/.github/CONTRIBUTING.md).
- [ ] I have completed the [pull request template](https://github.com/typicalbot/typicalbot/blob/master/.github/PULL_REQUEST_TEMPLATE.md).
- [ ] I have checked open [pull requests](https://github.com/typicalbot/typicalbot/pulls) for upcoming features and fixes.

2020-07-24 21:52 UTC, nsylke requested changes

2020-07-24 21:52 UTC, nsylke commented on src/commands/utility/randomuser.ts
> +            message.error(message.translate('utility/randomuser:MAXED'));
missing `return` before `message.error`.

2020-07-24 22:03 UTC, nsylke commented on etc/languages/en-US/utility/randomuser.json
> +    "MAXED": "Note: You can only select maximum of 10 users at random."
@tjrgg How does "You can select up to 10 users at a time."

2020-07-25 05:30 UTC, tjrgg commented on etc/languages/en-US/utility/randomuser.json
> +    "MAXED": "Note: You can only select up to 10 users at random."
```suggestion
    "MAXED": "You can only select up to 10 users at random."
```

2020-07-25 14:36 UTC, tjrgg approved these changes

2020-07-25 18:39 UTC, nsylke approved these changes

2020-07-26 13:35 UTC, merged